# Generated by Django 4.2.7 on 2023-11-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0002_rename_blog_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Date',
        ),
    ]
