# Generated by Django 4.2.7 on 2023-11-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0003_remove_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Completed',
        ),
    ]
